[package]
name = "jornet-cli"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
biscuit-auth = "2.2.0"
base64 = "0.13"
clap = { version = "3.2", features = ["derive"] }
